### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sash322** [matterpreter/DefenderCheck#8] opened 2019-04-12 18:28 UTC
When i run ./Defendercheck.exe , I got
 System.NullReferenceException: Object reference not set to an instance of an object.
 in DefenderCheck.Program.Setup()
 in DefenderCheck.Program.Main(String[] args)

**Comment by emanuelecesari** [comment] 2019-04-13 10:43
I got the same error 
![image](https://user-images.githubusercontent.com/12241058/56078520-0b4aff80-5de1-11e9-9aca-d3c149c7a210.png)

**Comment by matterpreter** [comment] 2019-04-14 18:09
Hey there. Please make sure that you are on latest. The `Setup()` method was modified and no longer has that error.

**Comment by matterpreter** [comment] 2019-04-16 17:20
@sash322 @emanuelecesari How's it looking on your end? If everything is resolved by pulling the latest version, I'll close this one out.

**Comment by emanuelecesari** [comment] 2019-04-16 21:09
I tried again even with the latest version I got the same error message.
I am testing on a Windows 10  build 17763

**Comment by matterpreter** [comment] 2019-04-17 18:03
That's really odd. That error is related to the `Setup()` method, so try commenting the call in `Main()` and recompiling. I am unable to reproduce on my end on a164a27.

**Comment by jakxx** [comment] 2019-04-18 14:20
In my case the crash was the result of a registry key not existing. Adding the registry key that defendercheck is looking for fixed the issue (see below)

![image](https://user-images.githubusercontent.com/1746973/56367325-044a3580-61c3-11e9-80d1-28cd72707e33.png)

Add a new Dword (32-bit) value of 0 in the location above and name it DisableAntiSpyware

**Comment by matterpreter** [comment] 2019-04-20 03:05
Ah okay. So there is a requirement that Defender be enabled, but realtime monitoring and automatic sample submission be disabled. In the original version of the `Setup()` method, I tried to determine the settings via the registry, but Windows really didn't like me touching them. 

I think the best thing I can do right now is to make a note in the README, but I would welcome any pull request to implement the check/disable as a feature.

**Comment by matterpreter** [comment] 2019-04-29 15:37
Made a note in the README. Closing for now.

**Closed by matterpreter** 2019-04-29 15:37 UTC
Labels: bug
